# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='The ISBN must be 13 digits.', regex='^[\\d]{13}$')])),
                ('asin', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='The ASIN must be 10 alphanumeric characters beginning with B00.', regex='^B00([a-zA-Z0-9]{7})$')])),
                ('book_type', models.CharField(choices=[('ebook', 'eBook'), ('paperback', 'Paperback'), ('hardback', 'Hardback')], max_length=9)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revshare_type', models.CharField(choices=[('gross', 'Gross'), ('net', 'Net')], max_length=5)),
                ('kindle_inclusive_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('kindle_non_inclusive_commission', models.DecimalField(decimal_places=3, max_digits=4)),
                ('apple_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nook_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('google_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('smashwords_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lightningsource_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('createspace_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('wholesale_commission', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('external_payee', models.BooleanField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(db_table='x_authors_titles', related_name='authors', to='source.Person')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Contract')),
                ('payees', models.ManyToManyField(db_table='x_payees_titles', related_name='payees', to='source.Person')),
            ],
            options={
                'db_table': 'titles',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.Title'),
        ),
    ]
