# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('kindle', 'Kindle'), ('apple', 'Apple'), ('nook', 'Nook'), ('google', 'Google'), ('smashwords', 'Smashwords'), ('lightningsource', 'Lightning Source'), ('createspace', 'CreateSpace')], default='kindle', max_length=15),
            preserve_default=False,
        ),
    ]
